k8sServiceHost: 192.168.1.11
k8sServicePort: 6443

kubeProxyReplacement: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

k8sClientRateLimit:
  qps: 100
  burst: 200

gatewayAPI:
  enabled: false

bpf:
  masquerade: true
  hostLegacyRouting: false

socketLB:
  hostNamespaceOnly: true

operator:
  replicas: 1 # Uncomment this if you only have one node
  rollOutPods: true

rollOutCiliumPods: true

securityContext:
  privileged: true

ipv6:
  enabled: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

ingressController:
  enabled: true
  default: true
  #enforceHttps: true
  loadbalancerMode: shared
  defaultSecretNamespace: cert-manager
  defaultSecretName: zerossl-prod
  service:
    loadBalancerIP: 192.168.1.220
