k8sServiceHost: 192.168.1.11
k8sServicePort: 6443

kubeProxyReplacement: true

ipam:
  mode: kubernetes

l2announcements:
  enabled: true

externalIPs:
  enabled: true

l7Proxy: true

bpf:
  masquerade: true

socketLB:
  hostNamespaceOnly: true

gatewayAPI:
  enabled: true

operator:
  replicas: 1 # One node
  rollOutPods: true

rollOutCiliumPods: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

envoy:
  enabled: false
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_BIND_SERVICE
        - CAP_NET_ADMIN
        - CAP_BPF
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

ipv6:
  enabled: false

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

prometheus:
  enabled: false

loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true

ingressController:
  enabled: true
  default: true
  enforceHttps: false
  loadbalancerMode: shared
  defaultSecretNamespace: cert-manager
  defaultSecretName: prod-cert-zerossl
  service:
    loadBalancerIP: 192.168.1.220
