apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      ref: nidr0x-homelab
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.48.0
      chart: argo-cd
      helm:
        valueFiles:
          - $nidr0x-homelab/argocd/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-motoradictos
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: motoradictos
  sources:
    - repoURL: https://github.com/nidr0x/motoradictos
      targetRevision: master
      ref: motoradictos
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
