apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
  namespace: kube-system
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.27
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
