apiVersion: v1
kind: Service
metadata:
  labels:
    app: teslamate
  name: teslamate
spec:
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: http
  selector:
    app: teslamate
