apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - cronjob.yaml
  - secret.yaml
configMapGenerator:
  - name: cloudflare-ddns-configmap
    files:
      - cloudflare-ddns.py
generatorOptions:
  disableNameSuffixHash: true
