apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: oauth2-proxy

  data:
    - secretKey: cookie-secret
      remoteRef:
        key: OAUTH2_COOKIE_SECRET
    - secretKey: client-secret
      remoteRef:
        key: OAUTH2_CLIENT_SECRET
    - secretKey: client-id 
      remoteRef:
        key: OAUTH2_CLIENT_ID
