config:
  existingSecret: oauth2-proxy
  configFile: |
    reverse_proxy = "true"
    redirect_url = "https://sso.nidr0x.win/oauth2/callback"
    upstreams = "static://202"
    email_domains = [ "*" ]
    ## custom (html) banner string
    # banner = ""
    ## custom (html) footer string
    footer = "-"
    provider = "google"
    whitelist_domains = [ ".nidr0x.win" ]
    cookie_domains = [ ".nidr0x.win" ]
    cookie_expire = "168h"
    cookie_secure = "false"
    cookie_httponly = "true"
    cookie_samesite = "lax"
    skip_provider_button= "true"
    pass_access_token = "true"
    pass_authorization_header = "true"
    set_authorization_header = "true"
    set_xauthrequest = "true"
    ## path for for sign_in.html and error.html templates
    #custom_templates_dir = "/etc/oauth2-proxy-template/"

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: oauth2-proxy-templates
    data:
      robots.txt: |-
        User-agent: *
        Disallow: /

extraVolumes:
  - name: html-template
    configMap:
      name: oauth2-proxy-templates

extraVolumeMounts:
  - mountPath: /etc/oauth2-proxy-template
    name: html-template

securityContext:
  enabled: true
  runAsNonRoot: true

authenticatedEmailsFile:
  enabled: false

service:
  type: ClusterIP
  portNumber: 4180

serviceAccount:
  enabled: true
  name: oauth2-proxy
  automountServiceAccountToken: true

ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: zerossl-prod
    external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
  hosts:
    - sso.nidr0x.win
  tls: []

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 128m
    memory: 64Mi

proxyVarsAsSecrets: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  timeoutSeconds: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1

httpScheme: http

htpasswdFile:
  enabled: false

sessionStorage:
  type: cookie

redis:
  enabled: false

metrics:
  enabled: true
  port: 44180
  servicemonitor:
    enabled: false

checkDeprecation: true

extraArgs:
  reverse-proxy: true
