config:
  existingSecret: oauth2-proxy
  configFile: |
    reverse_proxy = "true"
    redirect_url = "https://sso.nidr0x.win/oauth2/callback"
    upstreams = "static://202"
    email_domains = [ "*" ]
    ## custom (html) banner string
    # banner = ""
    ## custom (html) footer string
    footer = "-"
    provider = "google"
    whitelist_domains = [ ".nidr0x.win" ]
    cookie_domains = [ ".nidr0x.win" ]
    cookie_expire = "168h"
    cookie_secure = "false"
    cookie_httponly = "true"
    cookie_samesite = "lax"
    skip_provider_button= "true"
    pass_access_token = "true"
    pass_authorization_header = "true"
    set_authorization_header = "true"
    set_xauthrequest = "true"
    ## path for for sign_in.html and error.html templates
    #custom_templates_dir = "/etc/oauth2-proxy-template/"

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: oauth2-proxy-templates
    data:
      robots.txt: |-
        User-agent: *
        Disallow: /
      sign_in.html: |-
        {{define "sign_in.html"}}
        <!DOCTYPE html>
        <html lang="en" charset="utf-8">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
            <title>Sign In</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

            <style>
              body {
                height: 100vh;
              }
              .sign-in-box {
                max-width: 400px;
                margin: 1.25rem auto;
              }
              .logo-box {
                margin: 1.5rem 3rem;
              }
              footer a {
                text-decoration: underline;
              }
            </style>
          </head>
          <body class="has-background-light">
          <section class="section">
            <div class="box block sign-in-box has-text-centered">
              {{ if .LogoData }}
              <div class="block logo-box">
                {{.LogoData}}
              </div>
              {{ end }}

              <form method="GET" action="{{.ProxyPrefix}}/start">
                <input type="hidden" name="rd" value="{{.Redirect}}">
                  {{ if .SignInMessage }}
                  <p class="block">{{.SignInMessage}}</p>
                  {{ end}}
                  <button type="submit" class="button block is-primary">Sign in with {{.ProviderName}}</button>
              </form>

              {{ if .CustomLogin }}
              <hr>

              <form method="POST" action="{{.ProxyPrefix}}/sign_in" class="block">
                <input type="hidden" name="rd" value="{{.Redirect}}">

                <div class="field">
                  <label class="label" for="username">Username</label>
                  <div class="control">
                    <input class="input" type="text" placeholder="e.g. userx@example.com"  name="username" id="username">
                  </div>
                </div>

                <div class="field">
                  <label class="label" for="password">Password</label>
                  <div class="control">
                    <input class="input" type="password" placeholder="********" name="password" id="password">
                  </div>
                </div>
                <button class="button is-primary">Sign in</button>
              </form>
              {{ end }}
            </div>
          </section>

          <script>
              (function() {
                var inputs = document.getElementsByName('rd');
                for (var i = 0; i < inputs.length; i++)
                  inputs[i].value = window.location;
              })();
            if (window.location.hash) {
              (function() {
                for (var i = 0; i < inputs.length; i++) {
                  // Add hash, but make sure it is only added once
                  var idx = inputs[i].value.indexOf('#');
                  if (idx >= 0) {
                    // Remove existing hash from URL
                    inputs[i].value = inputs[i].value.substr(0, idx);
                  }
                  inputs[i].value += window.location.hash;
                }
              })();
            }
          </script>

          <footer class="footer has-text-grey has-background-light is-size-7">
            <div class="content has-text-centered">
              {{ if eq .Footer "-" }}
              {{ else if eq .Footer ""}}
              <p>Secured with <a href="https://github.com/oauth2-proxy/oauth2-proxy#oauth2_proxy" class="has-text-grey">OAuth2 Proxy</a> version {{.Version}}</p>
              {{ else }}
              <p>{{.Footer}}</p>
              {{ end }}
            </div>
          </footer>

          </body>
        </html>
        {{end}}
      error.html: |-
        {{define "error.html"}}
        <!DOCTYPE html>
        <html lang="en" charset="utf-8">
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
          <title>{{.StatusCode}} {{.Title}}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

        <script type="text/javascript">
          document.addEventListener('DOMContentLoaded', function() {
            let cardToggles = document.getElementsByClassName('card-toggle');
            for (let i = 0; i < cardToggles.length; i++) {
              cardToggles[i].addEventListener('click', e => {
                e.currentTarget.parentElement.parentElement.childNodes[3].classList.toggle('is-hidden');
              });
            }
          });
        </script>

        <style>
          body {
            height: 100vh;
          }
          .error-box {
            margin: 1.25rem auto;
            max-width: 600px;
          }
          .status-code {
            font-size: 12rem;
            font-weight: 600;
          }
          #more-info.card {
            border: 1px solid #f0f0f0;
          }
          footer a {
            text-decoration: underline;
          }
        </style>
        </head>
        <body class="has-background-light">
        <section class="section">
          <div class="box block error-box has-text-centered">
            <div class="status-code">{{.StatusCode}}</div>
            <div class="block">
              <h1 class="subtitle is-1">{{.Title}}</h1>
            </div>

            {{ if or .Message .RequestID }}
            <div id="more-info" class="block card is-fullwidth is-shadowless">
              <header class="card-header is-shadowless">
                <p class="card-header-title">More Info</p>
                <a class="card-header-icon card-toggle">
                  <i class="fa fa-angle-down"></i>
                </a>
              </header>
              <div class="card-content has-text-left is-hidden">
                {{ if .Message }}
                <div class="content">
                  {{.Message}}
                </div>
                {{ end }}
                {{ if .RequestID }}
                <div class="content">
                  Request ID: {{.RequestID}}
                </div>
                {{ end }}
              </div>
            </div>
            {{ end }}

            {{ if .Redirect }}
            <hr>

            <div class="columns">
              <div class="column">
                <form method="GET" action="{{.Redirect}}">
                  <button type="submit" class="button is-danger is-fullwidth">Go back</button>
                </form>
              </div>
              <div class="column">
                <form method="GET" action="{{.ProxyPrefix}}/sign_in">
                  <input type="hidden" name="rd" value="{{.Redirect}}">
                  <button type="submit" class="button is-primary is-fullwidth">Sign in</button>
                </form>
              </div>
            </div>
            {{ end }}

          </div>
        </section>

        <footer class="footer has-text-grey has-background-light is-size-7">
          <div class="content has-text-centered">
            {{ if eq .Footer "-" }}
            {{ else if eq .Footer ""}}
            <p>Secured with <a href="https://github.com/oauth2-proxy/oauth2-proxy#oauth2_proxy" class="has-text-grey">OAuth2 Proxy</a> version {{.Version}}</p>
            {{ else }}
            <p>{{.Footer}}</p>
            {{ end }}
          </div>
        </footer>

        </body>
        </html>
        {{end}}


extraVolumes:
- name: html-template
  configMap:
    name: oauth2-proxy-templates

extraVolumeMounts:
- mountPath: /etc/oauth2-proxy-template
  name: html-template

securityContext:
  enabled: true
  runAsNonRoot: true

authenticatedEmailsFile:
  enabled: false

service:
  type: ClusterIP
  portNumber: 4180

serviceAccount:
  enabled: true
  name: oauth2-proxy
  automountServiceAccountToken: true

ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: zerossl-prod
    external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
  hosts:
   - sso.nidr0x.win
  tls:

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 128m
    memory: 64Mi

proxyVarsAsSecrets: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  timeoutSeconds: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1

httpScheme: http

htpasswdFile:
  enabled: false

sessionStorage:
  type: cookie

redis:
  enabled: false

metrics:
  enabled: true
  port: 44180
  servicemonitor:
    enabled: false

checkDeprecation: true

extraArgs:
  reverse-proxy: true

