apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubepromstack-oauth2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: kubepromstack-oauth2

  data:
    - secretKey: GF_AUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: OAUTH2_CLIENT_SECRET
    - secretKey: GF_AUTH_GOOGLE_CLIENT_ID
      remoteRef:
        key: OAUTH2_CLIENT_ID
