apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubepromstack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: kubepromstack

  data:
    - secretKey: client-secret
      remoteRef:
        key: OAUTH2_CLIENT_SECRET
    - secretKey: client-id
      remoteRef:
        key: OAUTH2_CLIENT_ID
