prometheusOperator:
  # Relabeling job name for operator metrics
  serviceMonitor:
    relabelings:
    # Replace job value
    - sourceLabels:
      - __address__
      action: replace
      targetLabel: job
      replacement: prometheus-operator
  # Disable creation of kubelet service
  kubeletService:
    enabled: false
prometheus-node-exporter:
  fullnameOverride: "kubepromstack-prometheus-node-exporter"
kube-state-metrics:
  fullnameOverride: "kubepromstack-kube-state-metrics"
alertmanager:
  ingress:
    enabled: true
    hosts:
      - monitoring.nidr0x.win
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: zerossl-prod
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-stripprefix@kubernetescrd,kube-system-redirect-https@kubernetescrd,kube-system-oauth-auth-redirect@kubernetescrd
      external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
    path: /alertmanager
    tls:
      - hosts:
        - '*.nidr0x.win'
        secretName: zerossl-prod
  alertmanagerSpec:
    fullnameOverride: "kubepromstack-alertmanager"
    # Subpath /alertmanager configuration
    externalUrl: http://monitoring.nidr0x.win/alertmanager/
    routePrefix: /
    securityContext:
      runAsGroup: 2002
      runAsNonRoot: true
      runAsUser: 1001
      fsGroup: 2002
    # PVC configuration
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  # ServiceMonitor job relabel
  serviceMonitor:
    relabelings:
      # Replace job value
      - sourceLabels:
        - __address__
        action: replace
        targetLabel: job
        replacement: alertmanager
prometheus:
  ingress:
    enabled: true
    hosts:
      - monitoring.nidr0x.win
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: zerossl-prod
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-stripprefix@kubernetescrd,kube-system-redirect-https@kubernetescrd,kube-system-oauth-auth-redirect@kubernetescrd
      external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
    path: /prometheus
    tls:
      - hosts:
        - '*.nidr0x.win'
        secretName: zerossl-prod
  prometheusSpec:
    fullnameOverride: "kubepromstack-prometheus"
    # Subpath /prometheus configuration
    externalUrl: http://monitoring.nidr0x.win/prometheus/
    routePrefix: /
    securityContext:
      runAsGroup: 2002
      runAsNonRoot: true
      runAsUser: 1001
      fsGroup: 2002
    # Resources request and limits
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    # PVC configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  # ServiceMonitor job relabel
  serviceMonitor:
    relabelings:
      # Replace job value
      - sourceLabels:
        - __address__
        action: replace
        targetLabel: job
        replacement: prometheus
grafana:
  envFromSecret: kubepromstack-oauth2
  ingress:
    enabled: true
    hosts:
      - monitoring.nidr0x.win
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: zerossl-prod
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-stripprefix@kubernetescrd,kube-system-redirect-https@kubernetescrd
      external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
    path: /grafana
    tls:
      - hosts:
        - '*.nidr0x.win'
        secretName: zerossl-prod
  securityContext:
    runAsGroup: 2002
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 2002
  testFramework:
    enabled: false
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    type: pvc
    storageClassName: nfs
    accessModes:
    - ReadWriteOnce
    size: 4Gi
  fullnameOverride: "kubepromstack-grafana"
  assertNoLeakedSecrets: false
  plugins:
    - pr0ps-trackmap-panel
    - natel-plotly-panel
  # Configuring /grafana subpath
  grafana.ini:
    server:
      domain: monitoring.nidr0x.win
      root_url: "https://monitoring.nidr0x.win/grafana"
      #root_url: "%(protocol)s://%(domain)s:/grafana/"
      #serve_from_sub_path: false
    users:
      allow_sign_up: false
      auto_asign_org: true
      auto_assign_or_role: Admin
    auth:
      disable_login_form: true
    database:
      wal: false
    auth.google:
      enabled: true
      allow_sign_up: true
      auto_login: false
      client_id: $__env{GF_AUTH_GOOGLE_CLIENT_ID}
      client_secret: $__env{GF_AUTH_GOOGLE_CLIENT_SECRET}
      scopes: openid email profile
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      api_url: https://openidconnect.googleapis.com/v1/userinfo
      allowed_domains: gmail.com
      use_pkce: true
  # List of grafana plugins to be installed
  plugins:
    - grafana-piechart-panel
  # ServiceMonitor label and job relabel
  serviceMonitor:
    labels:
      release: kubepromstack
    relabelings:
      # Replace job value
      - sourceLabels:
        - __address__
        action: replace
        targetLabel: job
        replacement: grafana
  # Additional data source: Loki
  #additionalDataSources:
  #- name: Loki
  #  type: loki
  #  url: http://loki-gateway.logging.svc.cluster.local
  sidecar:
    dashboards:
      searchNamespace: ALL
# Disabling monitoring of K8s services.
# Monitoring of K3S components will be configured out of kube-prometheus-stack
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
# Disable K8S Prometheus Rules
# Rules for K3S components will be configured out of kube-prometheus-stack
defaultRules:
  create: true
  rules:
    etcd: false
    k8s: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: false
    kubeProxy: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false

namespaceOverride: kube-monitoring
nameOverride: ""
fullnameOverride: "kubepromstack"
releaseOverride: ""

