apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-certificate
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: cloudflare-certificate

  data:
    - secretKey: tls.crt
      remoteRef:
        key: CLOUDFLARE_CERTIFICATE_PEM
    - secretKey: tls.key
      remoteRef:
        key: CLOUDFLARE_CERTIFICATE_KEY
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: cloudflare
  namespace: kube-system

spec:
  defaultCertificate:
    secretName: cloudflare-certificate
