apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system
spec:
  certificates:
    - secretName: letsencrypt-prod
  defaultCertificate:
    secretName: letsencrypt-prod
