apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-auth-api
  namespace: kube-system
type: Opaque
data:
  dopplerToken: ZHAuc3QucHJkLlJYUklpZXdXTklLazA5YUVoMjNUU1NJMzNxN2k0bjE4WmxXWGdRcjY3QWo=
