apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml
    #  - secret/secret.yaml
  - ingress.yaml
