apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: motoradictos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for MotorAdictos
  destinations:
  - namespace: '*'
    name: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
