apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-yaml
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: adguardhome/
    repoURL: https://github.com/nidr0x/homelab/argocd/apps
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

