apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- ingress.yaml
- argocd-apps.yaml
- argocd-setup.yaml
- secret.yaml

helmChartInflationGenerator:
  - chartName: argo-cd
    chartVersion: 5.27.3
    chartRepoUrl: https://argoproj.github.io/argo-helm
    valuesMerge: merge
    values: values.yaml
    releaseName: argocd
    releaseNamespace: argocd
