apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    password: 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
    url: https://github.com/nidr0x/homelab
    username: not-used
    type: git
---
apiVersion: v1
kind: Secret
metadata:
    name: sso
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    dex.google.clientSecret: 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
    dex.google.clientID: 672885211243-a9de98uqbpcuf0vbltap4s6qm68jcqtq.apps.googleusercontent.com
---
apiVersion: v1
kind: Secret
metadata:
    name: doppler-token-auth-api
    namespace: kube-system
type: Opaque
stringData:
    dopplerToken: dp.st.prd.09wwt3iXwF7yJFNNKn4VvDYJKLiuwcRx5B9OYW5D3XY
---
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  name: "motoradictos"
  project: "motoradictos"
  server: "https://[2a01:4f8:1c1b:62f2::1]:6443"
  tlsClientConfig:
      caData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT1RnME9EQXpNelV3SGhjTk1qTXhNREk0TURnd05UTTFXaGNOTXpNeE1ESTFNRGd3TlRNMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT1RnME9EQXpNelV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVThlS0Nsd05qWHRVcGZuUE9KRDZNcjNobklTaTVtTVN0WEFBVGVQY1AKUmoyVmZtcnEvUjJlVjNuZG1ic09Sb2hzcHNxeGdkT2pVSU1oL3p2RWhRRWNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRCcG1mSFFyYmlQK1QvNmpuSmRQClVVRnYvbjR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnT0pBUTJkOWZwdWduekZ1akNPc3BPZHFIaEozZU1HNTgKNWRSbHYrL0FFa1FDSVFEaW9WUVVrUkpvYjZ2WC9ZUXR2azBKb0NuWWNDcEQ1QS9Ldng3VHF0M1ppZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      certData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJVCtxa1huRk5jZzB3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOams0TkRnd016TTFNQjRYRFRJek1UQXlPREE0TURVek5Wb1hEVEkwTVRBeQpOekE0TURVek5Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOQnVrUUhSUVRPVm1uQlgKZzFpd2E3ekhyMnQ2RTA5bkVrenNoZE0wdDFZaElaQ0VDOG0zTGRMS3JKY0xXSzNQaWJIUlh3ZWc5S2hVSEpEbApOTzgxU0JDalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUVlDTS9iNm9DbDFxbk42RWMxazBPeXd2RUZVekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXQ3aG5IU1Y0SStrK0RaNnlUMDVoUmh4NjFMTHp2d2J4WDNmak91S3lxZ2NDSVFDRlNQMHpCT0p4ajhMMApXZ3dZWkJVK01FUTk1aU5hb1V6U1EyTzZnaS9WWkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFMk9UZzBPREF6TXpVd0hoY05Nak14TURJNE1EZ3dOVE0xV2hjTk16TXhNREkxTURnd05UTTEKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFMk9UZzBPREF6TXpVd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBU0V3SHRlVVgyeDVuKzNsWlJjZjRPMkVGcVBMQ3ZuRlpnS3prVmM3dTdRCm9KRVNncUNSR3FEZVBBSDZDNVpWOU1EWkhRUW9kcGhxSC9xdFRGSFRsZmNVbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVHQWpQMitxQXBkYXB6ZWhITlpORApzc0x4QlZNd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ05WaVladkdEazQrOXEvSjdrRU5vTVdHbnJ2ZUJJRXZ1ClhpbEVrNUtQN1ZzQ0lRQ3d2aEIvbDhkSW5KL3VDL054R1RObEhaMzdodmtKM0RqUGpQa1A3ZlRIb3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
      keyData: "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUt0eW9JeEFrdm1jUTN1c2p6Tmp0VE8vSjc1UXpIU2tGbGVkcHlPVGJKNTNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMEc2UkFkRkJNNVdhY0ZlRFdMQnJ2TWV2YTNvVFQyY1NUT3lGMHpTM1ZpRWhrSVFMeWJjdAowc3FzbHd0WXJjK0pzZEZmQjZEMHFGUWNrT1UwN3pWSUVBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
