apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nidr0x-homelab
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: nidr0x-homelab

  data:
    - secretKey: password
      remoteRef:
        key: ARGOCD_GITHUB_TOKEN
    - secretKey: url
      remoteRef:
        key: ARGOCD_GITHUB_URL
    - secretKey: username
      remoteRef:
        key: ARGOCD_GITHUB_USERNAME
    - secretKey: type
      remoteRef:
        key: ARGOCD_GITHUB_TYPE
