apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    password: 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
    url: https://github.com/nidr0x/homelab
    username: not-used
    type: git
---
apiVersion: v1
kind: Secret
metadata:
    name: sso
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    dex.google.clientSecret: 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
    dex.google.clientID: 672885211243-a9de98uqbpcuf0vbltap4s6qm68jcqtq.apps.googleusercontent.com
---
apiVersion: v1
kind: Secret
metadata:
    name: doppler-token-auth-api
    namespace: kube-system
type: Opaque
stringData:
    dopplerToken: dp.st.prd.09wwt3iXwF7yJFNNKn4VvDYJKLiuwcRx5B9OYW5D3XY
