fullnameOverride: argocd

configs:
  params:
    # Run server without TLS
    # Traefik finishes TLS connections
    server.insecure: true
  rbac:
    policy.default: ""
    scopes: '[email, group]'
    policy.csv: |
      g, nidr0x@gmail.com, role:admin
  cm:
    admin.enabled: 'false'
    url: https://argocd.nidr0x.win
    statusbadge.enabled: 'false'
    dex.config: |
      connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: $sso:dex.google.clientID
            clientSecret: $sso:dex.google.clientSecret
          type: oidc
          id: google
          name: Google

    # Adding Applications health check
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        local status = obj.status
        if status.conditions ~= nil then
          for i, condition in ipairs(status.conditions) do
            if condition.type ~= nil and string.match(condition.type, '.*Error$') then
              hs.status = "Degraded"
              hs.message = condition.message
              return hs
            end
          end
        end
        if status.health ~= nil then
          local health = status.health
          hs.status = health.status
          if health.message ~= nil then
            hs.message = health.message
          end
          local syncStatus = (status.sync and status.sync.status or nil)
          if hs.status == "Healthy" and syncStatus ~= "Synced" then
            hs.status = "Progressing"
          end
        end
      end
      return hs
