fullnameOverride: argocd

configs:
  params:
    # Run server without TLS
    # Traefik finishes TLS connections
    server.insecure: true
  rbac:
    policy.default: ""
    scopes: '[email, group]'
    policy.csv: |
      g, nidr0x@gmail.com, role:admin
  cm:
    admin.enabled: 'false'
    url: https://argocd.nidr0x.win
    statusbadge.enabled: 'false'
    dex.config: |
      connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: $sso:dex.google.clientID
            clientSecret: $sso:dex.google.clientSecret
          type: oidc
          id: google
          name: Google

    # Adding Applications health check
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
          local syncStatus = (obj.status.sync and obj.status.sync.status or nil)
          if hs.status == "Healthy" and syncStatus ~= "Synced" then
            hs.status = "Progressing"
          end
          if obj.operationState ~= nil then
            local operationState = obj.operationState
            local retryLimit = (operationState.operation and operationState.operation.retry and operationState.operation.retry.limit or nil)
            local retryCount = (operationState.retryCount or nil)
            if retryLimit == retryCount and hs.status == "Progressing" then
              hs.status = "Degraded"
              hs.message = "Retry limit reached while syncing all Application"
            end
          end
        end
      end
      return hs
