fullnameOverride: argocd

configs:
  params:
    # Run server without TLS
    # Traefik finishes TLS connections
    server.insecure: true
  cm:
    admin.enabled: 'true'
    url: https://argocd.nidr0x.win
    statusbadge.enabled: 'false'
    policy.csv: |
      g, nidr0x@gmail.com, role:admin
    policy.default: role:readonly
    scopes: '[groups, email]'
    dex.config: |
      connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: 672885211243-a9de98uqbpcuf0vbltap4s6qm68jcqtq.apps.googleusercontent.com
            clientSecret: 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
            adminEmail: nidr0x@gmail.com
          type: oidc
          id: google
          name: Google

    # Adding Applications health check
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs
