apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguardhome-pv-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: adguardhome-data  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.1.10
      share: /nfs/adguard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguardhome-pv-data-local
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  hostPath:
    path: /opt/adguardhome
    type: DirectoryOrCreate
