apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
     volumes:
      - name: transmission-config
        persistentVolumeClaim:
          claimName: transmission-config-pvc
      - name: transmission-downloads
        persistentVolumeClaim:
          claimName: transmission-downloads-pvc
     containers:
        - name: deluge
          #image: ghcr.io/linuxserver/transmission:4.0.4
          image: ghcr.io/linuxserver/deluge:2.1.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              memory: 256Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 8112
          volumeMounts:
            - name: transmission-config
              mountPath: /config
            - name: transmission-downloads
              mountPath: /downloads
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 8112
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 2
            tcpSocket:
              port: 8112
            timeoutSeconds: 2
          env:
          - name: TZ
            value: "Europe/Madrid"
          - name: PUID
            value: "1001"
          - name: PGID
            value: "2002"
