apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: uptime-kuma-config # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.1.10
      share: /nfs/uptime-kuma
