apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguardhome
spec:
  destination:
    namespace: adguardhome
    server: https://kubernetes.default.svc
  project: default
  source:
    path: adguardhome/
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
