apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguardhome
spec:
  destination:
    namespace: adguardhome
    server: https://kubernetes.default.svc
  project: default
  source:
    # Enabling Recursive Resource Detection
    directory:
      recurse: false
    # Repo path
    path: adguardhome/
    # Repo URL
    repoURL: https://github.com/nidr0x/homelab
    # Branch, tag tracking
    targetRevision: master
  syncPolicy:
    # Automatic sync options
    automated:
      prune: true
      selfHeal: true
