apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: monitoring/node-problem-detector
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
