apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      ref: nidr0x-homelab
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.11.0
      helm:
        valueFiles:
          - $nidr0x-homelab/cert-manager/build/values.yaml
  syncPolicy:
    # Automatic sync options
    automated:
      prune: true
      selfHeal: true
