apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    # Repo path
    path: external-dns/
    # Repo URL
    repoURL: https://github.com/nidr0x/homelab
    # Branch, tag tracking
    targetRevision: master
  syncPolicy:
    # Automatic sync options
    automated:
      prune: true
      selfHeal: true
