apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
spec:
  destination:
    namespace: oauth2-proxy
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      ref: nidr0x-homelab
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      path: oauth2-proxy/
    - repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 6.17.0
      chart: oauth2-proxy
      helm:
        valueFiles:
          - $nidr0x-homelab/oauth2-proxy/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
