apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-reloader
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: secret-reloader/
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
