apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller-plans
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  source:
    path: cluster-components/upgrade-plans
    repoURL: https://github.com/nidr0x/homelab
    path: system-upgrade-controller/
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
