apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  source:
    path: traefik/
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
