apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
spec:
  destination:
    namespace: transmission
    server: https://kubernetes.default.svc
  project: everest
  source:
    path: transmission/
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
