apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring/uptime-kuma/
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
