apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: transmission-config # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.1.10
      share: /nfs/transmission/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: transmission-downloads # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.1.10
      share: /nfs/transmission/downloads
