apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.2
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 100Mi
            cpu: 25m
          limits:
            memory: 200Mi
            cpu: 100m
        args:
        - --source=ingress
        - --provider=cloudflare
        - --log-level=debug
        - --annotation-filter=external-dns.alpha.kubernetes.io/target
        - --cloudflare-proxied 
        env:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: CF_API_KEY
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: CF_API_EMAIL
