apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: external-dns

  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: CF_API_KEY
    - secretKey: CF_API_EMAIL
      remoteRef:
        key: CF_API_EMAIL
