fullnameOverride: cert-manager
maxConcurrentChallenges: 2

installCRDs: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi

ingressShim:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

webhook:
  enabled: true

cainjector:
  enabled: true
  replicaCount: 1

global:
  logLevel: 3

extraArgs:
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  - --dns01-recursive-nameservers-only
  - --feature-gates=ExperimentalGatewayAPISupport=true
